title:       DeckTech.net
description: "DeckTech has one mission: To build a self sustaining community that adds entertainment value to the CCGs we all enjoy. All CCG players welcome."
keywords: "CCG, TCG, Collectible card games, Trading card game, SW:CCG, ST:CCG, M:TG, Customizable Card Game, CCG, Star Wars CCG, Star Trek CCG, Card Gaming"
email:       info@decktech.net
markdown:    kramdown
logo:        false
#paginate:    5
baseurl:     ""
url:         "https://www.decktech.net"
excerpt_separator: N/A-------N/A
#plugins: [jekyll-gist]

#permalink: /:year/:month/:title.html
#permalink: /:categories/:title
permalink: /:title/

include:
  - _decks
  - _decks_indexes
  - _tournament_reports
  - _tournament_reports_indexes

exclude: 
  - requirements.txt
  - .git
  - .gitignore
  - .sass-cache
  - Gemfile
  - gruntfile.js
  - gulpfile.js
  - node_modules
  - package-lock.json
  - package.json
  - Rakefile
  - README.md
  - s3_website.yml
  - sass

showdates: false


#plugins:
#  - raw_tag.rb



